/*
 * Sun to USB keyboard adapter
 * Copyright (C) 2019  Simon Wendel
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include <stdint.h>

/**
 * Mirror the HID usage codes to those in HID-Project source, only cherry-
 * picking what we need for the Sun keyoard.
 */
enum HidUsageCode : uint8_t
{
    HID_KEYBOARD_A_AND_A = 0x04,
    HID_KEYBOARD_B_AND_B = 0x05,
    HID_KEYBOARD_C_AND_C = 0x06,
    HID_KEYBOARD_D_AND_D = 0x07,
    HID_KEYBOARD_E_AND_E = 0x08,
    HID_KEYBOARD_F_AND_F = 0x09,
    HID_KEYBOARD_G_AND_G = 0x0A,
    HID_KEYBOARD_H_AND_H = 0x0B,
    HID_KEYBOARD_I_AND_I = 0x0C,
    HID_KEYBOARD_J_AND_J = 0x0D,
    HID_KEYBOARD_K_AND_K = 0x0E,
    HID_KEYBOARD_L_AND_L = 0x0F,
    HID_KEYBOARD_M_AND_M = 0x10,
    HID_KEYBOARD_N_AND_N = 0x11,
    HID_KEYBOARD_O_AND_O = 0x12,
    HID_KEYBOARD_P_AND_P = 0x13,
    HID_KEYBOARD_Q_AND_Q = 0x14,
    HID_KEYBOARD_R_AND_R = 0x15,
    HID_KEYBOARD_S_AND_S = 0x16,
    HID_KEYBOARD_T_AND_T = 0x17,
    HID_KEYBOARD_U_AND_U = 0x18,
    HID_KEYBOARD_V_AND_V = 0x19,
    HID_KEYBOARD_W_AND_W = 0x1A,
    HID_KEYBOARD_X_AND_X = 0x1B,
    HID_KEYBOARD_Y_AND_Y = 0x1C,
    HID_KEYBOARD_Z_AND_Z = 0x1D,
    HID_KEYBOARD_1_AND_EXCLAMATION_POINT = 0x1E,
    HID_KEYBOARD_2_AND_AT = 0x1F,
    HID_KEYBOARD_3_AND_POUND = 0x20,
    HID_KEYBOARD_4_AND_DOLLAR = 0x21,
    HID_KEYBOARD_5_AND_PERCENT = 0x22,
    HID_KEYBOARD_6_AND_CARAT = 0x23,
    HID_KEYBOARD_7_AND_AMPERSAND = 0x24,
    HID_KEYBOARD_8_AND_ASTERISK = 0x25,
    HID_KEYBOARD_9_AND_LEFT_PAREN = 0x26,
    HID_KEYBOARD_0_AND_RIGHT_PAREN = 0x27,
    HID_KEYBOARD_ENTER = 0x28,
    HID_KEYBOARD_ESCAPE = 0x29,
    HID_KEYBOARD_DELETE = 0x2A,
    HID_KEYBOARD_TAB = 0x2B,
    HID_KEYBOARD_SPACEBAR = 0x2C,
    HID_KEYBOARD_MINUS_AND_UNDERSCORE = 0x2D,
    HID_KEYBOARD_EQUALS_AND_PLUS = 0x2E,
    HID_KEYBOARD_LEFT_BRACKET_AND_LEFT_CURLY_BRACE = 0x2F,
    HID_KEYBOARD_RIGHT_BRACKET_AND_RIGHT_CURLY_BRACE = 0x30,
    HID_KEYBOARD_BACKSLASH_AND_PIPE = 0x31,
    HID_KEYBOARD_SEMICOLON_AND_COLON = 0x33,
    HID_KEYBOARD_QUOTE_AND_DOUBLEQUOTE = 0x34,
    HID_KEYBOARD_GRAVE_ACCENT_AND_TILDE = 0x35,
    HID_KEYBOARD_COMMA_AND_LESS_THAN = 0x36,
    HID_KEYBOARD_PERIOD_AND_GREATER_THAN = 0x37,
    HID_KEYBOARD_SLASH_AND_QUESTION_MARK = 0x38,
    HID_KEYBOARD_CAPS_LOCK = 0x39,
    HID_KEYBOARD_F1 = 0x3A,
    HID_KEYBOARD_F2 = 0x3B,
    HID_KEYBOARD_F3 = 0x3C,
    HID_KEYBOARD_F4 = 0x3D,
    HID_KEYBOARD_F5 = 0x3E,
    HID_KEYBOARD_F6 = 0x3F,
    HID_KEYBOARD_F7 = 0x40,
    HID_KEYBOARD_F8 = 0x41,
    HID_KEYBOARD_F9 = 0x42,
    HID_KEYBOARD_F10 = 0x43,
    HID_KEYBOARD_F11 = 0x44,
    HID_KEYBOARD_F12 = 0x45,
    HID_KEYBOARD_PRINTSCREEN = 0x46,
    HID_KEYBOARD_SCROLL_LOCK = 0x47,
    HID_KEYBOARD_PAUSE = 0x48,
    HID_KEYBOARD_INSERT = 0x49,
    HID_KEYBOARD_HOME = 0x4A,
    HID_KEYBOARD_PAGE_UP = 0x4B,
    HID_KEYBOARD_DELETE_FORWARD = 0x4C,
    HID_KEYBOARD_END = 0x4D,
    HID_KEYBOARD_PAGE_DOWN = 0x4E,
    HID_KEYBOARD_RIGHTARROW = 0x4F,
    HID_KEYBOARD_LEFTARROW = 0x50,
    HID_KEYBOARD_DOWNARROW = 0x51,
    HID_KEYBOARD_UPARROW = 0x52,
    HID_KEYPAD_NUM_LOCK_AND_CLEAR = 0x53,
    HID_KEYPAD_DIVIDE = 0x54,
    HID_KEYPAD_MULTIPLY = 0x55,
    HID_KEYPAD_SUBTRACT = 0x56,
    HID_KEYPAD_ADD = 0x57,
    HID_KEYPAD_ENTER = 0x58,
    HID_KEYPAD_1_AND_END = 0x59,
    HID_KEYPAD_2_AND_DOWN_ARROW = 0x5A,
    HID_KEYPAD_3_AND_PAGE_DOWN = 0x5B,
    HID_KEYPAD_4_AND_LEFT_ARROW = 0x5C,
    HID_KEYPAD_5 = 0x5D,
    HID_KEYPAD_6_AND_RIGHT_ARROW = 0x5E,
    HID_KEYPAD_7_AND_HOME = 0x5F,
    HID_KEYPAD_8_AND_UP_ARROW = 0x60,
    HID_KEYPAD_9_AND_PAGE_UP = 0x61,
    HID_KEYPAD_0_AND_INSERT = 0x62,
    HID_KEYPAD_PERIOD_AND_DELETE = 0x63,
    HID_KEYBOARD_NON_US_BACKSLASH_AND_PIPE = 0x64,
    HID_KEYBOARD_APPLICATION = 0x65,
    HID_KEYBOARD_POWER = 0x66,
    HID_KEYBOARD_EXECUTE = 0x74,
    HID_KEYBOARD_HELP = 0x75,
    HID_KEYBOARD_MENU = 0x76,
    HID_KEYBOARD_SELECT = 0x77,
    HID_KEYBOARD_STOP = 0x78,
    HID_KEYBOARD_AGAIN = 0x79,
    HID_KEYBOARD_UNDO = 0x7A,
    HID_KEYBOARD_CUT = 0x7B,
    HID_KEYBOARD_COPY = 0x7C,
    HID_KEYBOARD_PASTE = 0x7D,
    HID_KEYBOARD_FIND = 0x7E,
    HID_KEYBOARD_MUTE = 0x7F,
    HID_KEYBOARD_VOLUME_UP = 0x80,
    HID_KEYBOARD_VOLUME_DOWN = 0x81,
    HID_KEYBOARD_LEFT_CONTROL = 0xE0,
    HID_KEYBOARD_LEFT_SHIFT = 0xE1,
    HID_KEYBOARD_LEFT_ALT = 0xE2,
    HID_KEYBOARD_LEFT_GUI = 0xE3,
    HID_KEYBOARD_RIGHT_CONTROL = 0xE4,
    HID_KEYBOARD_RIGHT_SHIFT = 0xE5,
    HID_KEYBOARD_RIGHT_ALT = 0xE6,
    HID_KEYBOARD_RIGHT_GUI = 0xE7
};
